tasks/app/urls.py
from django.urls import path
from . import views
from .views import FeedListView
urlpatterns = [
    path('',views.feedback,name='feedback'),
    path('feed/',FeedListView.as_view(),name='feed'),
]

tasks/formify/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('',include('django.contrib.auth.urls')),
]

tasks/tasks/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('',include('django.contrib.auth.urls')),
]

tasks/app/models.py
from django.db import models
from django.contrib.auth.models import User


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    subject = models.CharField(max_length=40)
    email = models.EmailField()
    comments = models.TextField()
    RATING_CHOICES = [
        (1, '1⭐'),
        (2, '2⭐'),
        (3, '3⭐'),
        (4, '4⭐'),
        (5, '5⭐'),
    ]
    rating = models.IntegerField(default=3,choices=RATING_CHOICES)

    def __str__(self):
        return f"{self.subject} {self.email} {self.comments} {self.rating}"

tasks/app/forms.py
from django import forms
from .models import Feedback
class FeedbackForm(forms.ModelForm):
    class Meta:
        model=Feedback
        fields=("subject","email","comments","rating")
 

tasks/app/views.py
from django.shortcuts import render,redirect
from django.core.mail import send_mass_mail,BadHeaderError
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.conf import settings
from .models import Feedback
from django.http import HttpResponse
from django.db.models import Count
from .forms import FeedbackForm
# Create your views here.
@login_required(login_url='/login')
def feedback(request):
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            rating = form.cleaned_data['rating']
            email = form.cleaned_data['email']
            comments = form.cleaned_data['comments']

            k = form.save(commit=False)
            k.user = request.user
            k.save()

            try:
                m1 = (
                    f"Feedback Form By {k.user}",
                    f"Subject: {subject}\nRating: {rating}\nFeedback: {comments}",
                    settings.EMAIL_HOST_USER,
                    [email]
                )
                m2 = (
                    "Thank you for your response",
                    "Please keep giving regular feedback",
                    settings.EMAIL_HOST_USER,
                    [email]
                )
                send_mass_mail((m1, m2), fail_silently=False)
            except BadHeaderError:
                return HttpResponse("Invalid header found.")
            
            return redirect('/feed')
    else:
        form = FeedbackForm()
    
    return render(request, 'app/feedback.html', {"form": form})
class FeedListView(LoginRequiredMixin,ListView):
    model = Feedback
    context_object_name = 'feed'
    template_name = 'feedback_list.html' 

    def get_queryset(self):
        return Feedback.objects.filter(user=self.request.user).order_by('-id')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        ratings = self.get_queryset().values_list('rating', flat=True)

        feedbacks_count = (
            Feedback.objects
            .values('user')
            .annotate(count=Count('id'))
            .order_by('-count')
        )

        labels = ['1⭐', '2⭐', '3⭐', '4⭐', '5⭐']
        ratings_data = [ratings.filter(rating=i).count() for i in range(1, 6)]

        context['ratings'] = ratings
        context['labels'] = labels
        context['ratings_data'] = ratings_data
        context['feedbacks_count'] = feedbacks_count

        return context
    
@login_required(login_url='/login')
def display(request):
    return render(request,'app/display.html')

tasks/app/templates/app/feedback.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Formify</title>
    <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/styles.css' %}">
  
</head>
<body>

{% if user.is_authenticated %}
<center>
    <span>
        <a href="/feed">
            <button type="submit" class="btn btn-outline-info m-3 text-center">CHECK PREVIOUS FORMS </button>
        </a>
        <a style="text-decoration:none;" href='/logout'><button type="button" class="btn btn-danger">Logout </button></a>
    </span>
</center>
{% else %}
<li class="nav-item">
    <a class="nav-link" href='/login'>Login</a>
</li>
{% endif %}
<br>
<div class="container">
    {% load crispy_forms_tags %}
    <form method="post">
        {% csrf_token %}
        
          <div class="form-group input-group mb-2">
            <div class="p-6 m-3 ">
           <input type="text" name="subject" maxlength="40" placeholder="Subject" required=""> </input>
           <input type="email" name="email" maxlength="254" required=""  placeholder="Enter your Email" id="id_email">
          </div>
          </div>
      
      
    <div class="form-group">
      <div class="col">
          <textarea name="comments" cols="40" rows="10" placeholder="Enter your Feedback here" required="" id="id_comments"></textarea>
      </div>
  </div>
  <div class="form-group">
    <label for="id_rating" class="col-form-label form-label">Rating</label>
    <div class="col">
        <select name="rating" id="id_rating" >
<option value="1">1⭐</option>

<option value="2">2⭐</option>

<option value="3" selected="">3⭐</option>

<option value="4">4⭐</option>

<option value="5">5⭐</option>

</select>
    </div>
</div><br>

        <div class="text-center">
            <button type="submit" class="btn btn-outline-info mb-2">Submit</button>
        </div>
    </form>
</div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

tasks/app/templates/app/feedback_list.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>My Forms</title>
    <meta name="description" content="">
    <link href="https://fonts.googleapis.com/css2?family=Merriweather:ital@1&display=swap" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="../static/app/style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'app/list.css' %}">
</head>
<body>
    <h2 class="text-center p-2 m-2">Your Feedbacks:</h2>
    <center>
        <span>
            <a href="{% url 'feedback' %}">
                <button type="submit" class="btn btn-outline-info m-3">ADD FEEDBACK</button>
            </a>
        </span>
    </center>
    <div class="charts-container">
      <div class="chart-container">
          <canvas id="ratingChart"></canvas>
      </div>

      <div class="chart-container">
          <canvas id="feedbacksChart"></canvas>
      </div>
  </div>
    <div class="container">

        <div class="row">
            {% for task in object_list %}
                {% if user == task.user %}
                    <div class="col-lg-6 col-md-12">
                        <div class="m-2 text-white">
                            <div class="card text-center text-white bg-black border-info mb-3">
                                <div class="card-header">
                                    <u>{{task.subject}}</u>    <span class="card-text">{{task.rating}}⭐</span>
                                </div>
                                <div class="card-body p-3 m-2">
                                    <p class="card-text">{{task.comments|capfirst}}</p>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}
            {% empty %}
            <br>
                <div class="col-12">
                    <h6>No items in list</h6>
                </div>
            {% endfor %}
        </div>
    </div>

  

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      document.addEventListener('DOMContentLoaded', function() {
        // Line chart
        var ctxRating = document.getElementById('ratingChart').getContext('2d');
        new Chart(ctxRating, {
            type: 'bar',
            data: {
                labels: {{ labels|safe }},
                datasets: [{
                    label: 'Your Ratings',
                    data: {{ ratings_data|safe }},
                    borderWidth: 1,
                    borderColor: 'rgba(255, 99, 132, 1)',
                    backgroundColor: 'rgba(255, 99, 132, 0.2)'
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            precision: 0
                        }
                    }
                }
            }
        });
    
        // Pie chart
        var ctxFeedbacks = document.getElementById('feedbacksChart').getContext('2d');
        new Chart(ctxFeedbacks, {
            type: 'bar',
            data: {
                labels: [{% for item in feedbacks_count %}"{{ item.user__username }}", {% endfor %}],
                datasets: [{
                    label: 'Users Feedbacks Count',
                    data: [{% for item in feedbacks_count %}{{ item.count }}, {% endfor %}],
                    backgroundColor: [
                        'rgba(255, 99, 132, 0.2)',
                        'rgba(54, 162, 235, 0.2)',
                        'rgba(255, 206, 86, 0.2)',
                        'rgba(75, 192, 192, 0.2)',
                        'rgba(153, 102, 255, 0.2)',
                        'rgba(255, 159, 64, 0.2)'
                    ],
                    borderColor: [
                        'rgba(255, 99, 132, 1)',
                        'rgba(54, 162, 235, 1)',
                        'rgba(255, 206, 86, 1)',
                        'rgba(75, 192, 192, 1)',
                        'rgba(153, 102, 255, 1)',
                        'rgba(255, 159, 64, 1)'
                    ],
                    borderWidth: 1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                scales: {
                    y: {
                        beginAtZero: true,
                        ticks: {
                            precision: 0
                        }
                    }
                }
            }
        });
    });
    
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/4.3.0/chart.min.js" integrity="sha512-mlz/Fs1VtBou2TrUkGzX4VoGvybkD9nkeXWJm3rle0DPHssYYx4j+8kIS15T78ttGfmOjH0lLaBXGcShaVkdkg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>